// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
void ui_event_Image1( lv_event_t * e);
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
void ui_event_Label3( lv_event_t * e);
extern lv_obj_t *ui_Label3;
void ui_event_Label4( lv_event_t * e);
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_Image11;
extern lv_obj_t *ui_Image12;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Label6;
void ui_event_Image2( lv_event_t * e);
extern lv_obj_t *ui_Image2;
void ui_event_Slider1( lv_event_t * e);
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_nastaveni_png);   // assets\nastaveni.png
LV_IMG_DECLARE( ui_img_baterka_podklad_mini_png);   // assets\baterka_podklad_mini.png
LV_IMG_DECLARE( ui_img_sipka_vpravo_zelena_png);   // assets\sipka_vpravo_zelena.png
LV_IMG_DECLARE( ui_img_sipka_vlevo_zelena_png);   // assets\sipka_vlevo_zelena.png
LV_IMG_DECLARE( ui_img_sipka_vlevo_bila_png);   // assets\sipka_vlevo_bila.png
LV_IMG_DECLARE( ui_img_sipka_vpravo_bila_png);   // assets\sipka_vpravo_bila.png
LV_IMG_DECLARE( ui_img_zeleny_dilek_dole_png);   // assets\zeleny_dilek_dole.png
LV_IMG_DECLARE( ui_img_zeleny_dilek_stred_png);   // assets\zeleny_dilek_stred.png
LV_IMG_DECLARE( ui_img_zeleny_dilek_nahore_png);   // assets\zeleny_dilek_nahore.png
LV_IMG_DECLARE( ui_img_nastaveni1_png);   // assets\nastaveni1.png
LV_IMG_DECLARE( ui_img_tachometr1_png);   // assets\tachometr1.png

LV_FONT_DECLARE( ui_font_Big);
LV_FONT_DECLARE( ui_font_Digital_speed);
LV_FONT_DECLARE( ui_font_medium);
LV_FONT_DECLARE( ui_font_medium_digital);
LV_FONT_DECLARE( ui_font_Mega);
LV_FONT_DECLARE( ui_font_Speedometer);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
